### ISSUE TITLE
After descrypt, it's not creating a new nds, like the command -hash

### ISSUE THREAD

**Issue by zackfcbr** [SabreTools/NDecrypt#14] opened 2024-03-20 13:09 UTC
I try all the command, only hash create a new file, and decrypt the file, a message saying that is done appears but not create a new file, it's working on the previous file?

**Comment by spiritfader** [comment] 2024-03-21 22:55
Yes. Here's a line from the readme demonstrating this as intended behavior.

`Note: This overwrites the input files, so make backups if you're working on your original, personal dumps.`

It sounds like you want to supply a duplicate of your file as the input to prevent the original copy from being overwritten and lost. Personally, I like to duplicate the original file and rename the new copy to denote whether it's going to be encrypted or decrypted, 
ie; renaming the new copy as `filename-dec` or `filename-enc` respectively. Good luck.

**Closed** 2024-11-15 02:47 UTC
